include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - cancel_subscriptions
    - prefer_single_quotes
    - avoid_print
    - annotate_overrides
    - avoid_as
    - avoid_annotating_with_dynamic
    - avoid_classes_with_only_static_members
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_unused_constructor_parameters
    - avoid_bool_literals_in_conditional_expressions
    - prefer_conditional_assignment
    - no_logic_in_create_state
    - require_trailing_commas
    - constant_identifier_names
    - directives_ordering
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - lines_longer_than_80_chars
    - prefer_const_constructors
    - prefer_is_empty
    - prefer_is_not_empty
    - sort_child_properties_last
    - sort_pub_dependencies
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_overrides
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_enums

analyzer:  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.iconfig.dart"