name: frontend
description: "Flutter frontend for an autonomous AI Agent in the Internet Computer"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:


  agent_dart: ^1.0.0-dev.35
  bloc: ^9.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.7
  get_it: ^8.0.3
  go_router: ^14.8.1
  injectable: ^2.5.0
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  


flutter:
  uses-material-design: true
  assets:
    - assets/logo2.svg
